### ISSUE TITLE
Host of PRM.Model.Protocol.RDP is not implemented

### ISSUE THREAD

**Issue by Paranoider** [1Remote/PRemoteM#248]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.0-alpha.2`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.5`       |
|OS             | `Windows 11 Pro 64-bits 10.0.22000.0 (2009)`                  |----》》这里的系统版本错误识别为win10，手动改为win111

## Error Info

Host of PRM.Model.Protocol.RDP is not implemented

## Stack Trace

```
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
20220529 08:05:20.348419[T:001][Bootstrapper.cs(OnStart:34)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220529 08:05:20.442233[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220529 08:05:22.063456[T:001][LauncherWindowViewModel.cs(HideMe:453)]		Debug
> Call HideMe()
20220029 09:00:32.927801[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 900, h = 801
20220029 09:00:35.028023[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220029 09:00:35.045020[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20220029 09:00:35.050269[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20220029 09:00:35.054006[T:001][Bootstrapper.cs(OnUnhandledException:98)]		Fatal
> System.NotImplementedException: Host of PRM.Model.Protocol.RDP is not implemented
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by VShawn** [comment]
你好，感谢你的问题反馈，请问我该执行怎样的步骤，来复现这一问题呢?
