### ISSUE TITLE
Crash each time when starting connection: Host of PRM.Model.Protocol.RDP is not implemented

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#254]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.0-alpha.2`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.5`       |
|OS             | `Windows 10 Enterprise 64-bits 10.0.19044.0 (2009)`                  |

## Error Info

Host of PRM.Model.Protocol.RDP is not implemented

## Stack Trace

```
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
20225005 17:50:43.211986[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20225005 17:50:44.566810[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Call HideMe()
20225005 17:50:44.568190[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225005 17:50:44.572709[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20225005 17:50:44.573851[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225005 17:50:44.575851[T:001][Bootstrapper.cs(OnUnhandledException:98)]		Fatal
> System.NotImplementedException: Host of PRM.Model.Protocol.RDP is not implemented
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.LauncherWindowViewModel.OpenSessionAndHide() in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowViewModel.cs:line 500
   at PRM.View.LauncherWindowView.TbKeyWord_OnPreviewKeyDown(Object sender, KeyEventArgs e) in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowView.xaml.cs:line 137
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.LauncherWindowViewModel.OpenSessionAndHide() in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowViewModel.cs:line 500
   at PRM.View.LauncherWindowView.TbKeyWord_OnPreviewKeyDown(Object sender, KeyEventArgs e) in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowView.xaml.cs:line 137
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
20225005 17:50:47.421486[T:007][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225005 17:50:47.434502[T:007][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:03.465190[T:001][Bootstrapper.cs(OnStart:34)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:03.513130[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:04.857963[T:001][LauncherWindowViewModel.cs(HideMe:453)]		Debug
> Call HideMe()
20225105 17:51:12.416524[T:001][LauncherWindowViewModel.cs(ShowMe:402)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20225105 17:51:13.197810[T:001][LauncherWindowViewModel.cs(HideMe:453)]		Debug
> Call HideMe()
20225105 17:51:13.202002[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:13.216327[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20225105 17:51:13.221002[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:13.224014[T:001][Bootstrapper.cs(OnUnhandledException:98)]		Fatal
> System.NotImplementedException: Host of PRM.Model.Protocol.RDP is not implemented
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.LauncherWindowViewModel.OpenSessionAndHide() in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowViewModel.cs:line 500
   at PRM.View.LauncherWindowView.TbKeyWord_OnPreviewKeyDown(Object sender, KeyEventArgs e) in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowView.xaml.cs:line 137
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.LauncherWindowViewModel.OpenSessionAndHide() in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowViewModel.cs:line 500
   at PRM.View.LauncherWindowView.TbKeyWord_OnPreviewKeyDown(Object sender, KeyEventArgs e) in D:\DemoProject\PRemoteM-NET6\Ui\View\LauncherWindowView.xaml.cs:line 137
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
20225105 17:51:20.282719[T:009][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:20.287001[T:009][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:21.399934[T:001][Bootstrapper.cs(OnStart:34)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:21.448211[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:22.671635[T:001][LauncherWindowViewModel.cs(HideMe:453)]		Debug
> Call HideMe()
20225105 17:51:25.038950[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 1147, h = 865
20225105 17:51:28.408271[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:28.425491[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20225105 17:51:28.429940[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:28.432772[T:001][Bootstrapper.cs(OnUnhandledException:98)]		Fatal
> System.NotImplementedException: Host of PRM.Model.Protocol.RDP is not implemented
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
20225105 17:51:30.202394[T:011][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:30.213389[T:011][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:31.643658[T:001][Bootstrapper.cs(OnStart:34)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:31.692162[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:32.918447[T:001][LauncherWindowViewModel.cs(HideMe:453)]		Debug
> Call HideMe()
20225105 17:51:34.549040[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 1147, h = 865
20225105 17:51:43.234962[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20225105 17:51:43.250766[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20225105 17:51:43.254959[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20225105 17:51:43.257630[T:001][Bootstrapper.cs(OnUnhandledException:98)]		Fatal
> System.NotImplementedException: Host of PRM.Model.Protocol.RDP is not implemented
   at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.Utils.ProtocolRunnerHostHelper.GetHostForInternalRunner(PrmContext context, ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\ProtocolRunnerHostHelper.cs:line 185
   at PRM.Service.SessionControlService.ConnectWithFullScreen(ProtocolBase server, Runner runner) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 185
   at PRM.Service.SessionControlService.ShowRemoteHost(Int64 serverId, String assignTabToken, String assignRunnerName) in D:\DemoProject\PRemoteM-NET6\Ui\Service\SessionControlService.cs:line 328
   at PRM.View.ProtocolBaseViewModel.<get_CmdConnServer>b__24_0(Object o) in D:\DemoProject\PRemoteM-NET6\Ui\View\ProtocolBaseViewModel.cs:line 63
   at Shawn.Utils.Wpf.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by majkinetor** [comment]
This bug quickly makes PRemoteM unusable with RDP. This time I switched to full screen after connecting, and then I can no longer start connection. Changing connection screen options doesn't help.

**Comment by VShawn** [comment]
this bug has been fixed in ticket https://github.com/1Remote/PRemoteM/issues/248
