### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#279]
This happened when computer was unattended with open connections. 

<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.0-alpha.3`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.8`       |
|OS             | `Windows 10 Enterprise 64-bits 10.0.19044.0 (2009)`                  |

## Error Info

Arithmetic operation resulted in an overflow.

## Stack Trace

```
   at PRM.View.MainWindowViewModel.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\DemoProject\PRemoteM-NET6\Ui\View\MainWindowViewModel.cs:line 313
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
20220118 00:01:07.068088[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220118 00:01:12.405447[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220118 00:01:13.596653[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220118 00:01:14.638250[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220418 00:04:44.460298[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 160, H = 28, Child NaN, NaN
20220418 00:04:47.889563[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220418 00:04:50.169319[T:020][(RunFromThreadPoolDispatchLoop:0)]		Debug
> MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 30, hash = 50153003)
20220418 00:04:50.169939[T:020][(RunFromThreadPoolDispatchLoop:0)]		Debug
> Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
20220418 00:04:50.170633[T:020][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> CloseEmptyWindows: closing tab(13604111)
20220418 00:04:50.171035[T:020][SessionControlService.cs(CleanupProtocolsAndWindows:719)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
20220418 00:04:50.171348[T:020][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Warning
> CloseEmptyWindows: 1 Empty Host closed
20220418 00:04:50.171673[T:020][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> Closing: 1 Empty Host.
20220418 00:04:50.171975[T:020][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Info
> CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
20220418 00:04:50.305451[T:001][(InvokeDelegateCore:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20222118 09:21:38.513871[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20222118 09:21:40.641330[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20222118 09:21:42.031899[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20222118 09:21:42.036556[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20222118 09:21:42.037083[T:001][SessionControlService.cs(CleanupProtocolsAndWindows:719)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20222118 09:21:42.080155[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1936, H = 1096, Child , 
20222118 09:21:42.085588[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initializing
20222118 09:21:42.086112[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: _rdpClient.Dispose()
20222118 09:21:42.086617[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
20222118 09:21:42.087485[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init CreateControl();
20222118 09:21:42.098018[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Static
20222118 09:21:42.098940[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init conn bar
20222118 09:21:42.099387[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Redirect
20222118 09:21:42.099971[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Display with ScaleFactor = 100, W = 1910, H = 1045
20222118 09:21:42.100320[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: Display init end: RDP.DesktopWidth = 1910, RDP.DesktopWidth = 1910,
20222118 09:21:42.100626[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Performance
20222118 09:21:42.100983[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RdpInit: DisplayPerformance = Auto, flag = 0
20222118 09:21:42.101289[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Gateway
20222118 09:21:42.101605[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initialized
20222118 09:21:42.105961[T:001][SessionControlService.cs(ConnectWithTab:259)]		Debug
> AxMsRdpClient09Host: Status => Connecting
20222118 09:21:42.106603[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Hosts.Count = 1, FullWin.Count = 0, _token2tabWindows.Count = 1
20222118 09:21:42.912892[T:001][(OnConnected:0)]		Debug
> RDP Host:  RdpOnOnConnected
20222118 09:21:42.913418[T:001][AxMsRdpClient09Host.cs(OnRdpClientConnected:159)]		Debug
> AxMsRdpClient09Host: Status => Connected
20222118 09:21:43.392469[T:001][(OnLoginComplete:0)]		Debug
> RDP Host:  RdpOnOnLoginComplete
20222118 09:21:43.678169[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1873, H = 1096, Child NaN, NaN
20222118 09:21:44.756446[T:003][AxMsRdpClient09Host.cs(<OnRdpClientLoginComplete>b__6_0:190)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20223418 09:34:56.907167[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 09:35:31.245365[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 09:35:31.831140[T:017][AxMsRdpClient09Host.xaml.cs(ResizeEndTimerOnElapsed:722)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20220218 11:02:50.024988[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20220218 11:02:55.466807[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20224118 11:41:14.943704[T:027][(RunFromThreadPoolDispatchLoop:0)]		Debug
> MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 30, hash = 54302657)
20224118 11:41:14.944805[T:027][(RunFromThreadPoolDispatchLoop:0)]		Debug
> Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
20224118 11:41:14.945483[T:027][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> CloseEmptyWindows: closing tab(51772594)
20224118 11:41:14.945871[T:027][SessionControlService.cs(CleanupProtocolsAndWindows:719)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
20224118 11:41:14.946185[T:027][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Warning
> CloseEmptyWindows: 1 Empty Host closed
20224118 11:41:14.946480[T:027][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> Closing: 1 Empty Host.
20224118 11:41:14.946813[T:027][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Info
> CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
20224118 11:41:15.072308[T:001][(InvokeDelegateCore:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20220618 12:06:24.783180[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20220618 12:06:25.738359[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220618 12:06:25.742990[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20220618 12:06:25.743507[T:001][SessionControlService.cs(CleanupProtocolsAndWindows:719)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20220618 12:06:25.777675[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1936, H = 1096, Child , 
20220618 12:06:25.782567[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initializing
20220618 12:06:25.783104[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: _rdpClient.Dispose()
20220618 12:06:25.783582[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
20220618 12:06:25.784145[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init CreateControl();
20220618 12:06:25.794249[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Static
20220618 12:06:25.794905[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init conn bar
20220618 12:06:25.795278[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Redirect
20220618 12:06:25.795769[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Display with ScaleFactor = 100, W = 1910, H = 1045
20220618 12:06:25.796117[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: Display init end: RDP.DesktopWidth = 1910, RDP.DesktopWidth = 1910,
20220618 12:06:25.796420[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Performance
20220618 12:06:25.796728[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RdpInit: DisplayPerformance = Auto, flag = 0
20220618 12:06:25.797023[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Gateway
20220618 12:06:25.797407[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initialized
20220618 12:06:25.800382[T:001][SessionControlService.cs(ConnectWithTab:259)]		Debug
> AxMsRdpClient09Host: Status => Connecting
20220618 12:06:25.800887[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Hosts.Count = 1, FullWin.Count = 0, _token2tabWindows.Count = 1
20220618 12:06:26.528963[T:001][(OnConnected:0)]		Debug
> RDP Host:  RdpOnOnConnected
20220618 12:06:26.529541[T:001][AxMsRdpClient09Host.cs(OnRdpClientConnected:159)]		Debug
> AxMsRdpClient09Host: Status => Connected
20220618 12:06:26.881750[T:001][(OnLoginComplete:0)]		Debug
> RDP Host:  RdpOnOnLoginComplete
20220618 12:06:27.176663[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1873, H = 1096, Child NaN, NaN
20220618 12:06:28.253679[T:026][AxMsRdpClient09Host.cs(<OnRdpClientLoginComplete>b__6_0:190)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20223518 12:35:15.742104[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 12:35:16.930862[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20223518 12:35:19.052082[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20223518 12:35:19.058293[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RemoteApp
20223518 12:35:20.194556[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20223518 12:35:21.191355[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20223518 12:35:23.533603[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 12:35:24.175333[T:011][AxMsRdpClient09Host.xaml.cs(ResizeEndTimerOnElapsed:722)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20223518 12:35:24.545482[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 12:35:25.387092[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20223518 12:35:27.101245[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20223518 12:35:27.107933[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20223518 12:35:27.108460[T:001][SessionControlService.cs(CleanupProtocolsAndWindows:719)]		Info
> CloseEmptyWindows: Current: Host = 1, Full = 0, Tab = 1, HostToBeDispose = 0, WindowToBeDispose = 0
20223518 12:35:27.112566[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initializing
20223518 12:35:27.112960[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: _rdpClient.Dispose()
20223518 12:35:27.113479[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
20223518 12:35:27.114115[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init CreateControl();
20223518 12:35:27.118723[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Static
20223518 12:35:27.119226[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init conn bar
20223518 12:35:27.119551[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Redirect
20223518 12:35:27.120033[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Display with ScaleFactor = 100, W = 1869, H = 1062
20223518 12:35:27.120387[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: Display init end: RDP.DesktopWidth = 1869, RDP.DesktopWidth = 1869,
20223518 12:35:27.120705[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Performance
20223518 12:35:27.121031[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RdpInit: DisplayPerformance = High, flag = 110000000
20223518 12:35:27.121330[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Gateway
20223518 12:35:27.121633[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initialized
20223518 12:35:27.128395[T:001][SessionControlService.cs(ConnectWithTab:259)]		Debug
> AxMsRdpClient09Host: Status => Connecting
20223518 12:35:27.131147[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Hosts.Count = 2, FullWin.Count = 0, _token2tabWindows.Count = 1
20223518 12:35:27.511732[T:001][(OnConnected:0)]		Debug
> RDP Host:  RdpOnOnConnected
20223518 12:35:27.512287[T:001][AxMsRdpClient09Host.cs(OnRdpClientConnected:159)]		Debug
> AxMsRdpClient09Host: Status => Connected
20223518 12:35:28.655615[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223518 12:35:34.531857[T:001][(OnLoginComplete:0)]		Debug
> RDP Host:  RdpOnOnLoginComplete
20223518 12:35:34.783576[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1873, H = 1096, Child NaN, NaN
20223518 12:35:35.858444[T:007][AxMsRdpClient09Host.cs(<OnRdpClientLoginComplete>b__6_0:190)]		Debug
> RDP resize to: W = 1857, H = 1050, ScaleFactor = 100
20223518 12:35:40.483899[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 160, H = 28, Child NaN, NaN
20223518 12:35:42.303647[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20223618 12:36:03.451549[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 1113, h = 789
20223618 12:36:03.465116[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 1101, h = 789
20223618 12:36:03.479099[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 1079, h = 789
20223618 12:36:03.491641[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 1063, h = 789
20223618 12:36:03.504416[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 1021, h = 789
20223618 12:36:03.517771[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 999, h = 789
20223618 12:36:03.530267[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 951, h = 789
20223618 12:36:03.542940[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 789
20223618 12:36:05.725076[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 787
20223618 12:36:05.741487[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 779
20223618 12:36:05.753147[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 772
20223618 12:36:05.765766[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 769
20223618 12:36:05.777482[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 755
20223618 12:36:05.789305[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 735
20223618 12:36:05.801278[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 724
20223618 12:36:05.812820[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 700
20223618 12:36:05.823894[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 689
20223618 12:36:05.834491[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 674
20223618 12:36:05.846921[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 650
20223618 12:36:05.859285[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 639
20223618 12:36:05.870836[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 623
20223618 12:36:05.882267[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 617
20223618 12:36:05.894849[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 610
20223618 12:36:05.906816[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 608
20223618 12:36:05.919006[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 607
20223618 12:36:05.930625[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 606
20223618 12:36:05.942932[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 603
20223618 12:36:05.955804[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 600
20223618 12:36:05.968530[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 596
20223618 12:36:05.980757[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 593
20223618 12:36:05.993020[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 590
20223618 12:36:06.005537[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 589
20223618 12:36:06.017637[T:001][(InvokeHandlersImpl:0)]		Info
> Main window resize to: w = 900, h = 587
20223618 12:36:06.239185[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20223618 12:36:06.239766[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20223618 12:36:33.284154[T:001][(WindowFilterMessage:0)]		Debug
> Tab size change to:W = 1486, H = 864, Child NaN, NaN
20223618 12:36:33.943481[T:027][AxMsRdpClient09Host.xaml.cs(ResizeEndTimerOnElapsed:722)]		Debug
> RDP resize to: W = 1857, H = 1050, ScaleFactor = 100
20225518 18:55:06.488285[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1936, H = 1096, Child NaN, NaN
20225518 18:55:06.838321[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20225518 18:55:06.839030[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20225518 18:55:06.839687[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)32768, (int)936606426944)
20225518 18:55:06.843961[T:001][Bootstrapper.cs(OnUnhandledException:153)]		Fatal
> System.OverflowException: Arithmetic operation resulted in an overflow.
   at PRM.View.MainWindowViewModel.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\DemoProject\PRemoteM-NET6\Ui\View\MainWindowViewModel.cs:line 313
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.View.MainWindowViewModel.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\DemoProject\PRemoteM-NET6\Ui\View\MainWindowViewModel.cs:line 313
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
20225518 18:55:06.992291[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20225518 18:55:06.993373[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)7, (int)0)
20225518 18:55:07.018285[T:031][AxMsRdpClient09Host.xaml.cs(ResizeEndTimerOnElapsed:722)]		Debug
> RDP resize to: W = 1920, H = 1050, ScaleFactor = 100
20225518 18:55:12.116690[T:001][(WndProc:0)]		Debug
> rdp.NotifyRedirectDeviceChange((uint)32768, (int)936606413712)
20225518 18:55:12.117331[T:001][Bootstrapper.cs(OnUnhandledException:153)]		Fatal
> System.OverflowException: Arithmetic operation resulted in an overflow.
   at PRM.View.MainWindowViewModel.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\DemoProject\PRemoteM-NET6\Ui\View\MainWindowViewModel.cs:line 313
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at PRM.View.MainWindowViewModel.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\DemoProject\PRemoteM-NET6\Ui\View\MainWindowViewModel.cs:line 313
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by VShawn** [comment]
this has been fix by 98d12e5e166f81703702f72bcedd21434fae3d9e, originate from the USB disk redirectiton.

The same code works on .NF4.8, and crashed on .Net6 whtich cause the USB disk redirectiton function to fail.
