### ISSUE TITLE
Crash when viewing note tooltips 

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#286]
I was viewing note tooltips on connections in list view, when it suddenly just crashed. 

<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.7.0-alpha.3`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.8`       |
|OS             | `Windows 10 Enterprise 64-bits 10.0.19044.0 (2009)`                  |

## Error Info

Object reference not set to an instance of an object.

## Stack Trace

```
   at System.Windows.Controls.Primitives.Popup.<HideWindow>b__130_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
20221113 00:11:32.183199[T:001][(OnDisconnected:0)]		Debug
> RDP Host: RdpOnDisconnected
20221113 00:11:32.184467[T:001][(RaiseOnOnDisconnected:0)]		Debug
> AxMsRdpClient09Host: Status => Disconnected
20221113 00:11:32.185664[T:001][AxMsRdpClient09Host.cs(OnRdpClientDisconnected:102)]		Warning
> RDP(brlog) exit with error code 3(You have been disconnected because another connection was made to the remote computer.)
20222113 00:21:13.429769[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20222113 00:21:14.750851[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20222113 00:21:14.755170[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20222113 00:21:14.755719[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 1, Full = 0, Tab = 1, HostToBeDispose = 0, WindowToBeDispose = 0
20222113 00:21:14.759507[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initializing
20222113 00:21:14.759879[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: _rdpClient.Dispose()
20222113 00:21:14.760240[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
20222113 00:21:14.760736[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init CreateControl();
20222113 00:21:14.765772[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Static
20222113 00:21:14.766291[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init conn bar
20222113 00:21:14.766607[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Redirect
20222113 00:21:14.767052[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Display with ScaleFactor = 100, W = 1847, H = 1045
20222113 00:21:14.767385[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: Display init end: RDP.DesktopWidth = 1847, RDP.DesktopWidth = 1847,
20222113 00:21:14.767749[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Performance
20222113 00:21:14.768047[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RdpInit: DisplayPerformance = Auto, flag = 0
20222113 00:21:14.768330[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Gateway
20222113 00:21:14.768618[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initialized
20222113 00:21:14.777499[T:001][SessionControlService.cs(ConnectWithTab:259)]		Debug
> AxMsRdpClient09Host: Status => Connecting
20222113 00:21:14.778114[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Hosts.Count = 2, FullWin.Count = 0, _token2tabWindows.Count = 1
20222113 00:21:15.953624[T:001][(OnConnected:0)]		Debug
> RDP Host:  RdpOnOnConnected
20222113 00:21:15.954180[T:001][AxMsRdpClient09Host.cs(OnRdpClientConnected:159)]		Debug
> AxMsRdpClient09Host: Status => Connected
20222113 00:21:16.358269[T:001][(OnLoginComplete:0)]		Debug
> RDP Host:  RdpOnOnLoginComplete
20222113 00:21:17.377821[T:012][AxMsRdpClient09Host.cs(<OnRdpClientLoginComplete>b__6_0:190)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20222513 00:25:07.275787[T:012][(RunFromThreadPoolDispatchLoop:0)]		Debug
> MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 30, hash = 32445972)
20222513 00:25:07.276393[T:012][(RunFromThreadPoolDispatchLoop:0)]		Debug
> Current: Host = 1, Full = 0, Tab = 1, HostToBeDispose = 1
20222513 00:25:07.277182[T:012][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 1, Full = 0, Tab = 1, HostToBeDispose = 1, WindowToBeDispose = 0
20222513 00:25:07.277580[T:012][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Info
> CloseMarkedProtocolHost: Current: Host = 1, Full = 0, Tab = 1, HostToBeDispose = 0
20222513 00:25:07.394008[T:001][(InvokeDelegateCore:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20222513 00:25:09.170622[T:001][(Invoke:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20222513 00:25:09.171327[T:012][(RunFromThreadPoolDispatchLoop:0)]		Debug
> MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 82, hash = 62007849)
20222513 00:25:09.171697[T:012][(RunFromThreadPoolDispatchLoop:0)]		Debug
> Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
20222513 00:25:09.172041[T:012][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> CloseEmptyWindows: closing tab(22853796)
20222513 00:25:09.172353[T:012][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
20222513 00:25:09.172617[T:012][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Warning
> CloseEmptyWindows: 1 Empty Host closed
20222513 00:25:09.172872[T:012][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> Closing: 1 Empty Host.
20222513 00:25:09.173121[T:012][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Info
> CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
20222513 00:25:09.179251[T:001][(InvokeDelegateCore:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20222113 11:21:05.020401[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20222113 11:21:10.499133[T:001][LauncherWindowViewModel.cs(OpenSessionAndHide:500)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20222113 11:21:10.506141[T:001][ProtocolRunnerHostHelper.cs(GetRunner:32)]		Warning
> we don't have a protocol named: RDP
20222113 11:21:10.506812[T:001][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20222113 11:21:10.556677[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1936, H = 1096, Child , 
20222113 11:21:10.562806[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initializing
20222113 11:21:10.563625[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: _rdpClient.Dispose()
20222113 11:21:10.564130[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
20222113 11:21:10.564732[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init CreateControl();
20222113 11:21:10.576780[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Static
20222113 11:21:10.577734[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init conn bar
20222113 11:21:10.578384[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Redirect
20222113 11:21:10.579048[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Display with ScaleFactor = 100, W = 1910, H = 1045
20222113 11:21:10.579487[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: Display init end: RDP.DesktopWidth = 1910, RDP.DesktopWidth = 1910,
20222113 11:21:10.579854[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Performance
20222113 11:21:10.580334[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RdpInit: DisplayPerformance = High, flag = 110000000
20222113 11:21:10.580684[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> RDP Host: init Gateway
20222113 11:21:10.581020[T:001][AxMsRdpClient09Host.xaml.cs(.ctor:79)]		Debug
> AxMsRdpClient09Host: Status => Initialized
20222113 11:21:10.585222[T:001][SessionControlService.cs(ConnectWithTab:259)]		Debug
> AxMsRdpClient09Host: Status => Connecting
20222113 11:21:10.585961[T:001][LauncherWindowView.xaml.cs(TbKeyWord_OnPreviewKeyDown:137)]		Debug
> Hosts.Count = 1, FullWin.Count = 0, _token2tabWindows.Count = 1
20222113 11:21:11.438132[T:001][(OnConnected:0)]		Debug
> RDP Host:  RdpOnOnConnected
20222113 11:21:11.438662[T:001][AxMsRdpClient09Host.cs(OnRdpClientConnected:159)]		Debug
> AxMsRdpClient09Host: Status => Connected
20222113 11:21:11.736615[T:001][(OnLoginComplete:0)]		Debug
> RDP Host:  RdpOnOnLoginComplete
20222113 11:21:12.040320[T:001][(InvokeHandlersImpl:0)]		Debug
> Tab size change to:W = 1873, H = 1096, Child NaN, NaN
20222113 11:21:13.125558[T:010][AxMsRdpClient09Host.cs(<OnRdpClientLoginComplete>b__6_0:190)]		Debug
> RDP resize to: W = 1847, H = 1045, ScaleFactor = 100
20222113 11:21:30.789477[T:010][(RunFromThreadPoolDispatchLoop:0)]		Debug
> MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 47, hash = 53760750)
20222113 11:21:30.789979[T:010][(RunFromThreadPoolDispatchLoop:0)]		Debug
> Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
20222113 11:21:30.790417[T:010][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> CloseEmptyWindows: closing tab(14983789)
20222113 11:21:30.790762[T:010][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
20222113 11:21:30.791071[T:010][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Warning
> CloseEmptyWindows: 1 Empty Host closed
20222113 11:21:30.791365[T:010][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Debug
> Closing: 1 Empty Host.
20222113 11:21:30.791667[T:010][SessionControlService.cs(<CloseProtocolHostAsync>b__0:525)]		Info
> CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
20222113 11:21:30.957088[T:001][(InvokeDelegateCore:0)]		Debug
> RDP Host: _rdpClient.Dispose()
20222713 11:27:57.309444[T:001][(InvokeMethod:0)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20222813 11:28:00.052635[T:001][(Execute:0)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20222813 11:28:09.377735[T:001][(PublicHooksFilterMessage:0)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20221513 15:15:49.268910[T:028][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20220313 20:03:51.246766[T:001][Bootstrapper.cs(OnStart:76)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220313 20:03:51.301455[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20220313 20:03:53.424110[T:001][LauncherWindowViewModel.cs(ShowMe:399)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20220313 20:03:57.435138[T:001][LauncherWindowViewModel.cs(ShowMe:399)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20220413 20:04:08.747297[T:001][LauncherWindowViewModel.cs(ShowMe:399)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20220413 20:04:12.226858[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 1187, h = 727
20220613 20:06:19.793842[T:001][LauncherWindowViewModel.cs(ShowMe:399)]		Debug
> Call shortcut to invoke launcher Visibility = Hidden
20220813 20:08:18.013020[T:008][SessionControlService.cs(PrintCacheCount:734)]		Info
> CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0, WindowToBeDispose = 0
20221013 20:10:19.136717[T:001][Bootstrapper.cs(OnStart:76)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20221013 20:10:19.186771[T:001][ConfigurationService.cs(Save:201)]		Debug
> SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
20221013 20:10:21.766156[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 1187, h = 727
20223613 20:36:06.399070[T:001][MainWindowView.xaml.cs(<.ctor>b__0:52)]		Info
> Main window resize to: w = 1187, h = 727
20223613 20:36:23.228468[T:001][Bootstrapper.cs(OnUnhandledException:153)]		Fatal
> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Controls.Primitives.Popup.<HideWindow>b__130_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Controls.Primitives.Popup.<HideWindow>b__130_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by majkinetor** [comment]
Its hard to reproduce but its possible, it seems like it involves opening launcher at the same time and leaving it open on the screen while hovering at list.

[debug.md](https://github.com/1Remote/PRemoteM/files/9677216/debug.md)


Not very important...

**Comment by VShawn** [comment]
Can not tell where the bug is, I'll start an investigation of this bug latter
