### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key:

### ISSUE THREAD

**Issue by yourh3ro** [1Remote/PRemoteM#309]
1. Export connetions from MRemoteNG csv
2. Try Import to PRemoteM

Error:

`[T:019][17:42:00.885]	`Debug`		
> System.ArgumentException: An item with the same key has already been added. Key: 0a85de34-347f-43bf-a65e-c4e02f75181f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at PRM.Utils.mRemoteNG.MRemoteNgImporter.GetMRemoteNgItems(String[]& csvLines) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\mRemoteNG\mRemoteNGImporter.cs:line 200
   at PRM.Utils.mRemoteNG.MRemoteNgImporter.FromCsv(String csvPath, List`1 icons) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\mRemoteNG\mRemoteNGImporter.cs:line 258
   at PRM.View.ServerListPageViewModel.<>c__DisplayClass49_0.<get_CmdImportFromCsv>b__1() in D:\DemoProject\PRemoteM-NET6\Ui\View\ServerListPageViewModel.cs:line 361

> StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at PRM.Utils.mRemoteNG.MRemoteNgImporter.GetMRemoteNgItems(String[]& csvLines) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\mRemoteNG\mRemoteNGImporter.cs:line 200
   at PRM.Utils.mRemoteNG.MRemoteNgImporter.FromCsv(String csvPath, List`1 icons) in D:\DemoProject\PRemoteM-NET6\Ui\Utils\mRemoteNG\mRemoteNGImporter.cs:line 258
   at PRM.View.ServerListPageViewModel.<>c__DisplayClass49_0.<get_CmdImportFromCsv>b__1() in D:\DemoProject\PRemoteM-NET6\Ui\View\ServerListPageViewModel.cs:line 361`
   
But I don't have any connections. I tried to delete all the program files, the database and do it from scratch. I always see this error.

**Comment by VShawn** [comment]
I made a test for the improt and confirm it works.

![image](https://user-images.githubusercontent.com/10143738/198754897-d93898f6-0017-450d-b82d-bdd20c1cd55a.png)


could you please check if there is a duplicate Id in your csv file form mRemoteNG?

![image](https://user-images.githubusercontent.com/10143738/198755022-fa315e3b-31f1-4966-92ac-24c707a4b615.png)

**Comment by yourh3ro** [comment]
Yes! I exported my entire list of 700+ connections and there were several duplicates. When I removed the duplicates, the connections started to be exported... I waited for more than an hour, but I didn't get it. Then I tried to export one group (~20 connections), everything turned out successfully. 
Still, there are very few connection directories like in mRemoteNG. Even with the number of ~ 100 connections, it is difficult to navigate, and if there are 200-400-600 of them...

**Comment by VShawn** [comment]
FYI, PRemoteM may hard to handle 700+ connections, it design for serve about 50+ connections. 

I never test the performance on that large number of connections.

That means, you may get stuck or frozen when search something with PRemoteM. 

So just let me know if you have any needs.

**Comment by majkinetor** [comment]
> FYI, PRemoteM may hard to handle 700+ connections, it design to serve about 50+ connections.

It should handle many more then 700 connections. What is so performance problematic in 1000 connections ? Not talking about Running the connections, but about managing them.

People that need remote management usually have more then 50.

**Comment by VShawn** [comment]
> What is so performance problematic in 1000 connections ? 

Because of the low render performance. New search keyword makes the list redraw, that cost much time Even though I have virtualization turned on.
